services:
  fastapibakcend:
    build: 
      context: ./backend_server
    ports:
      - "8085:8085"
    volumes:
      - /root/backend_server_data:/app/db
  
  nextfrontend:
    build: 
      context: ./web
    ports:
      - "3000:3000"
    volumes:
      - /root/backend_server_data/audiofile:/app/public/soundmp3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/stream_sys/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fastapibakcend
      - nextfrontend